/* Generated By:JavaCC: Do not edit this line. DXFParserConstants.java */
package cib.util.dxf.interpreter;

public interface DXFParserConstants {

  int EOF = 0;
  int EOL = 3;
  int SEC_START = 4;
  int SEC_END = 5;
  int FILE_EOF = 6;
  int S_HEADER = 7;
  int S_CLASSES = 8;
  int S_TABLES = 9;
  int S_BLOCKS = 10;
  int S_ENTITIES = 11;
  int S_OBJECTS = 12;
  int S_THUMBS = 13;
  int BLK_START = 14;
  int BLK_END = 15;
  int TABLE_START = 16;
  int TABLE_END = 17;
  int GROUP_CODE = 18;
  int TEXT = 19;
  int TOKEN_0 = 20;
  int TOKEN_9 = 21;
  int TOKEN_X = 22;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<EOL>",
    "<SEC_START>",
    "<SEC_END>",
    "<FILE_EOF>",
    "<S_HEADER>",
    "<S_CLASSES>",
    "<S_TABLES>",
    "<S_BLOCKS>",
    "<S_ENTITIES>",
    "<S_OBJECTS>",
    "<S_THUMBS>",
    "<BLK_START>",
    "<BLK_END>",
    "<TABLE_START>",
    "<TABLE_END>",
    "<GROUP_CODE>",
    "<TEXT>",
    "<TOKEN_0>",
    "<TOKEN_9>",
    "<TOKEN_X>",
  };

}
