/* Generated By:JavaCC: Do not edit this line. DXFParserTokenManager.java */
package cib.util.dxf.interpreter;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import cib.util.dxf.Attributes;
import cib.util.dxf.AttributesAdapter;
import cib.util.dxf.ContentHandler;
import cib.util.dxf.GroupCode;
import cib.util.dxf.QuitDXFParserException;

public class DXFParserTokenManager implements DXFParserConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjMoveStringLiteralDfa0_0()
{
   return jjMoveNfa_0(1, 0);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 254;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  else if (curChar == 32)
                     jjCheckNAddStates(3, 40);
                  else if (curChar == 10)
                  {
                     if (kind > 3)
                        kind = 3;
                  }
                  else if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 0;
                  if (curChar == 50)
                     jjCheckNAddStates(41, 54);
                  else if (curChar == 48)
                     jjCheckNAddStates(55, 70);
                  else if (curChar == 57)
                     jjCheckNAddTwoStates(27, 34);
                  if (curChar == 57)
                     jjAddStates(71, 72);
                  break;
               case 0:
                  if (curChar == 10 && kind > 3)
                     kind = 3;
                  break;
               case 2:
                  if (curChar == 10 && kind > 3)
                     kind = 3;
                  break;
               case 3:
                  if (curChar == 57)
                     jjAddStates(71, 72);
                  break;
               case 4:
               case 10:
                  if (curChar == 10)
                     jjCheckNAddStates(73, 75);
                  break;
               case 5:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(73, 75);
                  break;
               case 6:
               case 8:
                  if (curChar == 10 && kind > 21)
                     kind = 21;
                  break;
               case 7:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 9:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 12:
               case 18:
                  if (curChar == 10)
                     jjCheckNAddStates(76, 78);
                  break;
               case 13:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(76, 78);
                  break;
               case 14:
               case 16:
                  if (curChar == 10 && kind > 22)
                     kind = 22;
                  break;
               case 15:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 17:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 19:
                  if (curChar == 32)
                     jjCheckNAddStates(3, 40);
                  break;
               case 20:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(20, 28);
                  break;
               case 21:
                  if (curChar == 57)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 22:
                  if (curChar == 10)
                     jjCheckNAddTwoStates(23, 25);
                  break;
               case 23:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddTwoStates(23, 25);
                  break;
               case 24:
                  if (curChar == 10 && kind > 1)
                     kind = 1;
                  break;
               case 25:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 26:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 27:
                  if (curChar == 57)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 28:
                  if (curChar == 57)
                     jjCheckNAdd(27);
                  break;
               case 29:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(29, 35);
                  break;
               case 30:
                  if (curChar == 57)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 31:
                  if (curChar == 10)
                     jjCheckNAddTwoStates(32, 33);
                  break;
               case 32:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddTwoStates(32, 33);
                  break;
               case 33:
                  if (curChar == 10 && kind > 2)
                     kind = 2;
                  break;
               case 34:
                  if (curChar == 57)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 35:
                  if (curChar == 57)
                     jjCheckNAdd(34);
                  break;
               case 36:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(36, 37);
                  break;
               case 37:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(49, 50);
                  break;
               case 38:
               case 50:
                  if (curChar == 10)
                     jjCheckNAdd(48);
                  break;
               case 40:
               case 42:
                  if (curChar == 10 && kind > 4)
                     kind = 4;
                  break;
               case 41:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 49:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 51:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(51, 52);
                  break;
               case 52:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(63, 64);
                  break;
               case 53:
               case 64:
                  if (curChar == 10)
                     jjCheckNAdd(62);
                  break;
               case 55:
               case 57:
                  if (curChar == 10 && kind > 5)
                     kind = 5;
                  break;
               case 56:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 63:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 65:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(65, 66);
                  break;
               case 66:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(74, 75);
                  break;
               case 67:
               case 75:
                  if (curChar == 10)
                     jjCheckNAdd(73);
                  break;
               case 69:
               case 71:
                  if (curChar == 10 && kind > 6)
                     kind = 6;
                  break;
               case 70:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 74:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 76:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(76, 77);
                  break;
               case 77:
                  if (curChar == 50)
                     jjCheckNAddTwoStates(88, 89);
                  break;
               case 78:
               case 89:
                  if (curChar == 10)
                     jjCheckNAdd(87);
                  break;
               case 80:
               case 82:
                  if (curChar == 10 && kind > 7)
                     kind = 7;
                  break;
               case 81:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 88:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 90:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(90, 91);
                  break;
               case 91:
                  if (curChar == 50)
                     jjCheckNAddTwoStates(103, 104);
                  break;
               case 92:
               case 104:
                  if (curChar == 10)
                     jjCheckNAdd(102);
                  break;
               case 94:
               case 96:
                  if (curChar == 10 && kind > 8)
                     kind = 8;
                  break;
               case 95:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 103:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 105:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(105, 106);
                  break;
               case 106:
                  if (curChar == 50)
                     jjCheckNAddTwoStates(117, 118);
                  break;
               case 107:
               case 118:
                  if (curChar == 10)
                     jjCheckNAdd(116);
                  break;
               case 109:
               case 111:
                  if (curChar == 10 && kind > 9)
                     kind = 9;
                  break;
               case 110:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 117:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 119:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(119, 120);
                  break;
               case 120:
                  if (curChar == 50)
                     jjCheckNAddTwoStates(131, 132);
                  break;
               case 121:
               case 132:
                  if (curChar == 10)
                     jjCheckNAdd(130);
                  break;
               case 123:
               case 125:
                  if (curChar == 10 && kind > 10)
                     kind = 10;
                  break;
               case 124:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 131:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 133:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(133, 134);
                  break;
               case 134:
                  if (curChar == 50)
                     jjCheckNAddTwoStates(147, 148);
                  break;
               case 135:
               case 148:
                  if (curChar == 10)
                     jjCheckNAdd(146);
                  break;
               case 137:
               case 139:
                  if (curChar == 10 && kind > 11)
                     kind = 11;
                  break;
               case 138:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 147:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 149:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(149, 150);
                  break;
               case 150:
                  if (curChar == 50)
                     jjCheckNAddTwoStates(162, 163);
                  break;
               case 151:
               case 163:
                  if (curChar == 10)
                     jjCheckNAdd(161);
                  break;
               case 153:
               case 155:
                  if (curChar == 10 && kind > 12)
                     kind = 12;
                  break;
               case 154:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 162:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 164:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(164, 165);
                  break;
               case 165:
                  if (curChar == 50)
                     jjCheckNAddTwoStates(184, 185);
                  break;
               case 166:
               case 185:
                  if (curChar == 10)
                     jjCheckNAdd(183);
                  break;
               case 168:
               case 170:
                  if (curChar == 10 && kind > 13)
                     kind = 13;
                  break;
               case 169:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 184:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 166;
                  break;
               case 186:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(186, 187);
                  break;
               case 187:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(197, 198);
                  break;
               case 188:
               case 198:
                  if (curChar == 10)
                     jjCheckNAdd(196);
                  break;
               case 190:
               case 192:
                  if (curChar == 10 && kind > 14)
                     kind = 14;
                  break;
               case 191:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 190;
                  break;
               case 197:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 188;
                  break;
               case 199:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(199, 200);
                  break;
               case 200:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(211, 212);
                  break;
               case 201:
               case 212:
                  if (curChar == 10)
                     jjCheckNAdd(210);
                  break;
               case 203:
               case 205:
                  if (curChar == 10 && kind > 15)
                     kind = 15;
                  break;
               case 204:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 203;
                  break;
               case 211:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 213:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(213, 214);
                  break;
               case 214:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(224, 225);
                  break;
               case 215:
               case 225:
                  if (curChar == 10)
                     jjCheckNAdd(223);
                  break;
               case 217:
               case 219:
                  if (curChar == 10 && kind > 16)
                     kind = 16;
                  break;
               case 218:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 217;
                  break;
               case 224:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 215;
                  break;
               case 226:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(226, 227);
                  break;
               case 227:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(238, 239);
                  break;
               case 228:
               case 239:
                  if (curChar == 10)
                     jjCheckNAdd(237);
                  break;
               case 230:
               case 232:
                  if (curChar == 10 && kind > 17)
                     kind = 17;
                  break;
               case 231:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 230;
                  break;
               case 238:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 228;
                  break;
               case 240:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(240, 241);
                  break;
               case 241:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(247, 248);
                  break;
               case 242:
               case 248:
                  if (curChar == 10)
                     jjCheckNAddStates(79, 81);
                  break;
               case 243:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(79, 81);
                  break;
               case 244:
               case 246:
                  if (curChar == 10 && kind > 20)
                     kind = 20;
                  break;
               case 245:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 244;
                  break;
               case 247:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 242;
                  break;
               case 249:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(249, 3);
                  break;
               case 250:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(250, 11);
                  break;
               case 251:
                  if (curChar == 57)
                     jjCheckNAddTwoStates(27, 34);
                  break;
               case 252:
                  if (curChar == 48)
                     jjCheckNAddStates(55, 70);
                  break;
               case 253:
                  if (curChar == 50)
                     jjCheckNAddStates(41, 54);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 5:
                  jjAddStates(73, 75);
                  break;
               case 13:
                  jjAddStates(76, 78);
                  break;
               case 23:
                  jjAddStates(82, 83);
                  break;
               case 32:
                  jjAddStates(84, 85);
                  break;
               case 39:
                  if (curChar == 78)
                     jjAddStates(86, 87);
                  break;
               case 43:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 44:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 45:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 47:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 48:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 54:
                  if (curChar == 67)
                     jjAddStates(88, 89);
                  break;
               case 58:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 59:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 60:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 61:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 62:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 68:
                  if (curChar == 70)
                     jjAddStates(90, 91);
                  break;
               case 72:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 73:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 79:
                  if (curChar == 82)
                     jjAddStates(92, 93);
                  break;
               case 83:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 84:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 85:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 86:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 87:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 93:
                  if (curChar == 83)
                     jjAddStates(94, 95);
                  break;
               case 97:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 98:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 99:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 100:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 101:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 102:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 108:
                  if (curChar == 83)
                     jjAddStates(96, 97);
                  break;
               case 112:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 113:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 114:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 115:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 116:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 122:
                  if (curChar == 83)
                     jjAddStates(98, 99);
                  break;
               case 126:
                  if (curChar == 75)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 127:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 129:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 130:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 136:
                  if (curChar == 83)
                     jjAddStates(100, 101);
                  break;
               case 140:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 141:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 142:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 143:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 144:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 143;
                  break;
               case 145:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 146:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               case 152:
                  if (curChar == 83)
                     jjAddStates(102, 103);
                  break;
               case 156:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 157:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 156;
                  break;
               case 158:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 159:
                  if (curChar == 74)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 160:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 159;
                  break;
               case 161:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 160;
                  break;
               case 167:
                  if (curChar == 69)
                     jjAddStates(104, 105);
                  break;
               case 171:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 172:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 173:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 174:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 173;
                  break;
               case 175:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 174;
                  break;
               case 176:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 175;
                  break;
               case 177:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 178:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 177;
                  break;
               case 179:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 178;
                  break;
               case 180:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 179;
                  break;
               case 181:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 180;
                  break;
               case 182:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 183:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 182;
                  break;
               case 189:
                  if (curChar == 75)
                     jjAddStates(106, 107);
                  break;
               case 193:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 189;
                  break;
               case 194:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 195:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 196:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 202:
                  if (curChar == 75)
                     jjAddStates(108, 109);
                  break;
               case 206:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 202;
                  break;
               case 207:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 206;
                  break;
               case 208:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 207;
                  break;
               case 209:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 208;
                  break;
               case 210:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 216:
                  if (curChar == 69)
                     jjAddStates(110, 111);
                  break;
               case 220:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 216;
                  break;
               case 221:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 220;
                  break;
               case 222:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 221;
                  break;
               case 223:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 222;
                  break;
               case 229:
                  if (curChar == 66)
                     jjAddStates(112, 113);
                  break;
               case 233:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 229;
                  break;
               case 234:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 235:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 234;
                  break;
               case 236:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 237:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 236;
                  break;
               case 243:
                  jjAddStates(79, 81);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 5:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(73, 75);
                  break;
               case 13:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(76, 78);
                  break;
               case 23:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(82, 83);
                  break;
               case 32:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(84, 85);
                  break;
               case 243:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(79, 81);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 254 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   11, 17, 18, 20, 28, 29, 35, 36, 37, 51, 52, 65, 66, 76, 77, 90, 
   91, 105, 106, 119, 120, 133, 134, 149, 150, 164, 165, 186, 187, 199, 200, 213, 
   214, 226, 227, 240, 241, 249, 3, 250, 11, 88, 89, 103, 104, 117, 118, 131, 
   132, 147, 148, 162, 163, 184, 185, 49, 50, 63, 64, 74, 75, 197, 198, 211, 
   212, 224, 225, 238, 239, 247, 248, 9, 10, 5, 7, 8, 13, 15, 16, 243, 
   245, 246, 23, 25, 32, 33, 41, 42, 56, 57, 70, 71, 81, 82, 95, 96, 
   110, 111, 124, 125, 138, 139, 154, 155, 169, 170, 191, 192, 204, 205, 218, 219, 
   231, 232, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default : 
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0x73fff9L, 
};
static final long[] jjtoSkip = {
   0x6L, 
};
protected JavaCharStream input_stream;
private final int[] jjrounds = new int[254];
private final int[] jjstateSet = new int[508];
protected char curChar;
public DXFParserTokenManager(JavaCharStream stream){
   if (JavaCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public DXFParserTokenManager(JavaCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(JavaCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 254; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(JavaCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

}
